# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-01-09 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20190109_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tv',
            name='total_seasons',
        ),
    ]
