# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-01-10 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_remove_tv_total_seasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='dir',
            name='tv',
        ),
        migrations.DeleteModel(
            name='Dir',
        ),
        migrations.DeleteModel(
            name='Tv',
        ),
    ]
